groups:

recipes:
    global:
        - applications::bash
        - applications::ssh_config
        - applications::mysql
    mac_os_x:
        - osxdefaults::set_computer_name
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::set_terminal_profile
        - osxdefaults::disable_natural_scrolling
attributes:
    mysql_root_password: "password"
    osxdefaults:
        computername: airK
    homebrewalt:
        apps:
            - bash-completion
            - wget
            - pwgen
            - htop-osx
            - watch
            - rsync
        cask_apps:
            - dropbox
            - onepassword
            - textwrangler
#            - intellij-idea-ultimate13
            - sourcetree
            - charles
            - cleanmymac
            - skype
            - twitter
            - google-hangouts
            - growlnotify
            - flash
            - java
