groups:
    - nodejs
recipes:
    global:
        - applications::ssh_config
        - applications::mysql
        - applications::bash
attributes:
    homebrewalt:
        apps:
            - bash-completion
    mysql_root_password: "password"
    git:
        name: Kyle Quevillon
        email: flexmonkeypatches@gmail.com
    authorization:
        sudo:
            users:
                - kyle
            passwordless: true
            include_sudoers_d: true     

    homebrewalt:
        apps:
            - ant
            - tomcat
            - wget
            - pwgen
            - htop-osx
            - watch
            - rsync
        cask_apps:
            - dropbox
            - onepassword
            - textwrangler
            - intellij-idea
            - sourcetree
            - charles
            - cleanmymac
            - timemachineeditor
            - skype
            - google-hangouts
            - growlnotify
            - teleport
            - flash
            - java7
