groups:
    - bash
    - nodejs-extras
recipes:
    global:
        - applications::ssh_config
        - applications::mysql
    mac_os_x:
        - sudoalt::default
        - osxdefaults::set_computer_name
        - osxdefaults::check_for_software_updates_daily
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::set_terminal_profile
        - osxdefaults::disable_natural_scrolling
        - osxdefaults::set_screensaver_preferences
#        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_set_magnification_on
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::use_name_and_password_on_loginscreen
        
attributes:
    mysql_root_password: "password"
    osxdefaults:
        computername: airK
    git:
        name: Kyle Quevillon
        email: flexmonkeypatches@gmail.com
    authorization:
        sudo:
            users:
                - kyle
            passwordless: true
            include_sudoers_d: true     

    homebrewalt:
        apps:
            - ant
            - tomcat
            - wget
            - pwgen
            - htop-osx
            - watch
            - rsync
        cask_apps:
            - dropbox
            - onepassword
            - textwrangler
            - intellij-idea
            - sourcetree
            - charles
            - cleanmymac
            - timemachineeditor
            - skype
            - google-hangouts
            - growlnotify
            - teleport
            - flash
            - java7
