recipes:
    global:
        - dotfiles::bash_it
        - dotfiles::inputrc
        - dotfiles::gitconfig
        - dotfiles::workspace
        - dotfiles::vim
        - dotfiles::sshconfig
        - applications::bash
attributes:
    homebrewalt:
        apps:
            - bash-completion
    dotfiles:
        vimusers:
            - root
            - kyle
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
                - vim-css-color: https://github.com/ap/vim-css-color
