recipes:
    mac_os_x:
        - nodejs::default    # Installs nodejs and installs all nodejs packages mentioned in the nodejs:apps attribute   
attributes:
    nodejs:
        apps:
            - uglify-js
            - uglifycss
            - bower
            - grunt
            - grunt-cli
            - karma
            - karma-cli
            - karma-jasmine@0.1.5
            - karma-sinon
            - karma-coverage
            - karma-requirejs
            - karma-html-reporter
            - karma-phantomjs-launcher
            - karma-chrome-launcher
            - karma-firefox-launcher
            - karma-safari-launcher
            - karma-ie-launcher
            - protractor
            - protractor-html-screenshot-reporter
            - underscore
            - less
